name: 'Parse Title and Body'
description: 'Parses the GitHub issue body and issue comment body to extract app and version.'
inputs:
  body:
    description: 'The full text of the GitHub issue and issue comment body.'
    required: true
  title:
    # New input for the issue title
    description: 'The full text of the GitHub issue title.'
    required: true
outputs:
  app:
    description: 'The extracted application name.'
  version:
    description: 'The extracted version number.'
  title-app:
    # New output for the app name from the title
    description: 'The extracted application name from the title.'
  build-args:
    description: 'The extracted application build arguments.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.body }}
  - ${{ inputs.title }}
