name: Auto sync image to docker hub
on:
  workflow_call:
    inputs:
      fromImage:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo fromImage
        run: | 
          echo "fromImage is ${{ inputs.fromImage }}"
          user=${{ github.event.sender.login }}
          echo "user=$user"
          actor=${{ github.actor }}
          echo "actor=$actor"
          event_name=${{ github.event_name }}
          echo "event_name=$event_name"
  build-images:
    if: ( inputs.fromImage != '')
    name: Auto tag  app image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: check podman
        run: |
          sudo podman version

      - name: Auto build image
        env:
          registry: ${{ vars.D_D_REGISTRY_NAME }}
          repo: ${{ vars.D_C_REGISTRY_REPOSITORY }}
          username: ${{ vars.D_C_REGISTRY_REPOSITORY }}
          password: ${{ secrets.D_C_REGISTRY_TOKEN }}
        run: |
          sudo podman run -it --rm -v ${PWD}:/workspace -w /workspace quay.io/skopeo/stable:latest \
            sync --src docker --dest docker --all ${{ github.event.inputs.fromImage }} ${registry}/${repo} \
            --dest-username ${username} --dest-password ${password} --keep-going --retry-times 2
          if [ $? -ne 0 ]; then
            echo "⚠️  Warning: Build for version ${{ github.event.inputs.fromImage }} failed, but continuing..."
          fi