name: Auto build Docker image
on:
  issue_comment:
    types:
      - created
jobs:
  check-accepted:
    runs-on: ubuntu-latest
    permissions: read-all
    outputs:
      has_accepted: ${{ steps.check-label.outputs.has_accepted }}
    steps:
      - name: Check for 'accepted' label
        id: check-label
        uses: actions/github-script@v6
        with:
          script: |
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number
            });
            
            const hasAccepted = issue.labels.some(label => 
              label.name.toLowerCase() === 'accepted'
            );
            core.setOutput('has_accepted', hasAccepted.toString());
      - name: Complete
        run: |
          echo "If accepted? ${{ steps.check-label.outputs.has_accepted }}"
          echo "Output Type: $(echo ${{ steps.check-label.outputs.has_accepted }} | jq type)"
  resolve-image-info:
    needs:
      - check-accepted
    if: ${{ needs.check-accepted.outputs.has_accepted == 'true' && startswith(github.event.comment.body, '/imagebuild_dockerimages') }}
    uses: ./.github/workflows/resolve-image-info.yml
    permissions: read-all
    with:
      body: ${{github.event.comment.body}}
      title: ${{github.event.issue.title}}
  start-building:
    needs:
      - resolve-image-info
    uses: ./.github/workflows/autobuild-dockerfiles.yml
    permissions: read-all
    with: 
      app: ${{ needs.resolve-image-info.outputs.app }}
      version: ${{ needs.resolve-image-info.outputs.version }}
      build-args: ${{ needs.resolve-image-info.outputs.build-args }}
  add-tips:
    needs:
      - resolve-image-info
      - start-building
    uses: ./.github/workflows/add-tips.yml
    permissions:
      issues: write
    with:
      body: ${{github.event.comment.body}}
      app: ${{ needs.resolve-image-info.outputs.app }}
      version: ${{ needs.resolve-image-info.outputs.version }}