name: Auto build DOCKER image
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      version:
        required: true
        type: string
      build-args:
        required: true
        type: string

jobs:
  build_apps:
    name: Auto build app image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64,arm64 ]
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Image
        env:
          registry: ${{ vars.D_D_REGISTRY_NAME }}
          username: ${{ vars.D_D_REGISTRY_REPOSITORY }}
          repo: ${{ vars.D_D_REGISTRY_REPOSITORY }}
          password: ${{ secrets.D_D_REGISTRY_TOKEN }}
          app: ${{ inputs.app }}
          version: ${{ inputs.version }}
          arch: ${{ matrix.arch }}
          build_args: "${{ inputs.build-args }}"
        run: .github/scripts/dockers.sh

  build_manifest:
    needs:
      - build_apps
    name: Auto manifest app image
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Manifest Image
        env:
          registry: ${{ vars.D_D_REGISTRY_NAME }}
          username: ${{ vars.D_D_REGISTRY_REPOSITORY }}
          repo: ${{ vars.D_D_REGISTRY_REPOSITORY }}
          password: ${{ secrets.D_D_REGISTRY_TOKEN }}
          app: ${{ inputs.app }}
          version: ${{ inputs.version }}
        run: .github/scripts/manifest-docker.sh
